name: Build Docker and Deploy on Prod

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Build the Docker image
        run: docker build . --tag irobire/boat-manager:latest

      - name: Docker Push
        run: docker push irobire/boat-manager:latest
      - name: Restart the docker microservice
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker compose --profile prod --env-file env.prod stop 
            docker compose --profile prod --env-file env.prod pull 
            docker compose --profile prod --env-file env.prod up --no-start app
            docker compose --profile prod --env-file env.prod start app
